# Generated by Django 5.1 on 2024-10-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0021_alter_infra_路線名_alter_table_dxf_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("file_name", models.CharField(max_length=255)),
            ],
        ),
    ]
