# Generated by Django 5.1 on 2024-10-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0022_uploadlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="S3Upload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="uploads/")),
            ],
        ),
    ]
