# Generated by Django 5.1 on 2024-10-21 13:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0023_s3upload"),
    ]

    operations = [
        migrations.DeleteModel(
            name="S3Upload",
        ),
    ]
