# Generated by Django 4.2.7 on 2024-10-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0024_delete_s3upload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bridgepicture",
            name="picture_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
