# Generated by Django 5.1 on 2024-11-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0025_alter_bridgepicture_picture_number"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bridgepicture",
            name="unique_bridge_picture",
        ),
        migrations.RemoveConstraint(
            model_name="fullreportdata",
            name="unique_parts_damage",
        ),
        migrations.AddConstraint(
            model_name="bridgepicture",
            constraint=models.UniqueConstraint(
                fields=(
                    "image",
                    "damage_coordinate_x",
                    "damage_coordinate_y",
                    "span_number",
                    "table",
                    "infra",
                    "article",
                ),
                name="unique_bridge_picture",
            ),
        ),
        migrations.AddConstraint(
            model_name="fullreportdata",
            constraint=models.UniqueConstraint(
                fields=(
                    "parts_name",
                    "damage_name",
                    "parts_split",
                    "join",
                    "this_time_picture",
                    "infra",
                    "article",
                    "damage_coordinate_x",
                    "damage_coordinate_y",
                    "span_number",
                    "special_links",
                ),
                name="unique_parts_damage",
            ),
        ),
    ]
