# Generated by Django 4.2.7 on 2024-11-04 01:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0026_remove_bridgepicture_unique_bridge_picture_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Damage",
        ),
        migrations.DeleteModel(
            name="DamageReport",
        ),
        migrations.DeleteModel(
            name="Image",
        ),
        migrations.DeleteModel(
            name="Panorama",
        ),
        migrations.DeleteModel(
            name="Photo",
        ),
        migrations.DeleteModel(
            name="UploadLog",
        ),
    ]
